---
# tasks file for pk_stepcli
- name: Install dependencies
  ansible.builtin.include_tasks:
    file: "./base_workflow/01_install_dependencies.yml"

- name: Add Service User
  ansible.builtin.include_tasks:
    file: "./base_workflow/02_create_serviceuser.yml"

- name: Install Step CLI
  ansible.builtin.include_tasks:
    file: "./base_workflow/03_install_stepcli.yml"

- name: Install Root Certificate
  ansible.builtin.include_tasks:
    file: "./base_workflow/04_install_rootca.yml"

- name: Get Leaf Certificate
  ansible.builtin.include_tasks:
    file: "./base_workflow/05_make_initialcertificates.yml"

- name: Install Automatic Renewal
  ansible.builtin.include_tasks:
    file: "./base_workflow/06_install_renewalservices.yml"

- name: Configure known services
  ansible.builtin.include_tasks:
    file: "./base_workflow/07_install_renewalservices.yml"